### ISSUE TITLE
How would one use this in express?

### ISSUE THREAD

**Issue by shoshomiga** [milesbarr/r10#1]

**Comment by milesbarr** [comment]
Hi shoshomiga,

I updated the library to integrate easily with Express.

Simply set the view engine in your Express app to `r10`.
```js
app.set('view engine', 'r10');
```
There is information about using layouts in the [README](https://github.com/milesbarr/r10#express-integration) and an [an example Express app](https://github.com/milesbarr/r10/tree/master/examples/example-express-app) for reference.
